### ISSUE TITLE
go.mod

### ISSUE THREAD

**Issue by vooon** [stevemeier/mirrorlist#1]
Hello,

Why not to use go modules? That simplify dependency management a lot!

**Comment by stevemeier** [comment]
Done.

Could you check that it works? Thanks!

**Comment by vooon** [comment]
Hello,

Yes, it works fine. Except that i had to run `go get -t -u ./...` to update deps because i have compile warnings for sqlite.

My other suggestion is not to place two files with `main()` into the same package.
Usually `cmd/<binary-name>/main.go` used.

**Comment by stevemeier** [comment]
Thanks for the suggestion. I have now moved the respective files into separate directories.

**Comment by vooon** [comment]
Now it's possible to `go get`:
```
$ go get github.com/stevemeier/mirrorlist/mirrorlist
$ go get github.com/stevemeier/mirrorlist/mirrorlist_updater
```

Thanks!
