### ISSUE TITLE
Where can I get the configure file generate-mirrorlist-cache.cfg

### ISSUE THREAD

**Issue by awsome0305** [stevemeier/mirrorlist#2]
When I use the flowing command

./target/debug/generate-mirrorlist-cache 
Error reading configuration file /etc/mirrormanager/generate-mirrorlist-cache.cfg

Where can I get the configure file generate-mirrorlist-cache.cfg?

**Comment by stevemeier** [comment]
Hello,

there is no such binary (generate-mirrorlist-cache) or config file (generate-mirrorlist-cache.cfg).
Are you sure this is the right repository?

**Comment by awsome0305** [comment]
@stevemeier I'm sorry that is the other repository.

**Comment by stevemeier** [comment]
No worries, I'll close this issue then.
